# Generated by Django 3.2.11 on 2022-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('book_id', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField()),
                ('pages', models.IntegerField(default=6)),
                ('language', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
