# Generated by Django 3.2.11 on 2022-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='overview',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
